package com.invictus.nkoba.nkoba.api;

import com.invictus.nkoba.nkoba.models.Credentials;
import com.invictus.nkoba.nkoba.models.CredentialsResponse;

import io.reactivex.Flowable;
import retrofit2.Response;
import retrofit2.http.Body;
import retrofit2.http.Field;
import retrofit2.http.FormUrlEncoded;
import retrofit2.http.GET;
import retrofit2.http.Headers;
import retrofit2.http.POST;

/**
 * Created by invictus on 2/25/18.
 */

public interface KoobaServerApi {

    /**
     * The is generated by facebook
     */
    @FormUrlEncoded
    @POST("sessions")
    Flowable<Response<Object>> authenticate(@Field("authorization_code") String auth);

    @POST("user/credentials")
    Flowable<Response<Object>> postUpdateCredentials(@Body CredentialsResponse credentials);

    @GET("kooba/state")
    Flowable<Response<Object>> getKoobaState();

}
