package com.invictus.nkoba.nkoba.api;

import io.reactivex.Flowable;
import retrofit2.Response;
import retrofit2.http.Field;
import retrofit2.http.FormUrlEncoded;
import retrofit2.http.GET;
import retrofit2.http.POST;

/**
 * Created by invictus on 2/25/18.
 */

public interface KoobaServerApi {

    /**
     * The is generated by facebook
     */
    @FormUrlEncoded
    @POST("sessions")
    Flowable<Response<Object>> authenticate(@Field("authorization_code") String auth);
}
