package com.invictus.nkoba.nkoba.api;

import com.invictus.nkoba.nkoba.models.Credentials;
import com.invictus.nkoba.nkoba.models.CredentialsResponse;

import io.reactivex.Flowable;
import retrofit2.Response;
import retrofit2.http.Body;
import retrofit2.http.Field;
import retrofit2.http.FormUrlEncoded;
import retrofit2.http.GET;
import retrofit2.http.Headers;
import retrofit2.http.POST;
import retrofit2.http.Query;

/**
 * Created by invictus on 2/25/18.
 */

public interface KoobaServerApi {

    /**
     * The is generated by facebook
     */
    @FormUrlEncoded
    @POST("sessions")
    Flowable<Response<Object>> authenticate(@Field("authorization_code") String auth);

    @POST("user/credentials")
    Flowable<Response<Object>> postUpdateCredentials(@Body CredentialsResponse credentials);

    @GET("kooba/state")
    Flowable<Response<Object>> getKoobaState();

    @POST("loan/request")
    Flowable<Response<Object>> requestLoan(@Query("payment_period_id") int settingId, @Query("amount_string") String amountString);

    @GET("kooba/loan")
    Flowable<Response<Object>> getLoanPayment();

    @GET("user/notifications")
    Flowable<Response<Object>> getUserNotification(@Query("page") int page);
}
